services:
  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./react:/app
    ports:
      - "5173:5173"
    command: bash -c "npm install && npm run dev -- --host"

  nest:
    image: node:20
    working_dir: /app
    volumes:
      - ./nest:/app
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run start:dev"
    networks:
      - backend
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
