services:
  nest:
    image: node:20-buster
    working_dir: /app
    environment:
      - DB_HOST=${DB_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./nest:/app
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run start:dev"
    networks:
      - backend
  db:
    image: mysql:8.1.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
